title: fuchen2020
description: My Blog
author: fuchen2020
logo: /static/img/avatar.png
github: https://github.com/fuchen2020
about: Freelance developer

baseurl: "https://fuchen2020.github.io"
url: "https://fuchen2020.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
